"""
Convert Solafune annotations to YOLO segment format.
YOLO format: <class_id> <x1> <y1> <x2> <y2> ... <xn> <yn> (normalized 0-1)

Usage: python convert_to_yolo.py
"""

import os
import json
import shutil
import random
from pathlib import Path
from tqdm import tqdm


# ==================== CONFIG ====================
class Config:
    SOURCE_IMAGES = Path("dataset/train_images")
    SOURCE_ANNOTATIONS = Path("dataset/train_annotations.json")
    
    OUTPUT_DIR = Path("datasets/yolo_tree")
    TRAIN_RATIO = 0.85  # 85% train, 15% val
    
    # Class mapping
    CLASS_MAP = {
        'individual_tree': 0,
        'group_of_trees': 1
    }
    
    SEED = 42


config = Config()


def convert_polygon_to_yolo(polygon_coords, img_width, img_height):
    """
    Convert flat polygon coords [x1, y1, x2, y2, ...] to YOLO normalized format.
    
    YOLO format: x1 y1 x2 y2 ... (all values normalized 0-1)
    """
    normalized = []
    for i in range(0, len(polygon_coords), 2):
        x = polygon_coords[i] / img_width
        y = polygon_coords[i + 1] / img_height
        # Clamp to 0-1
        x = max(0.0, min(1.0, x))
        y = max(0.0, min(1.0, y))
        normalized.extend([x, y])
    return normalized


def convert_annotations():
    print("=" * 60)
    print("CONVERTING SOLAFUNE TO YOLO FORMAT")
    print("=" * 60)
    
    # Create output directories
    train_images = config.OUTPUT_DIR / "images" / "train"
    val_images = config.OUTPUT_DIR / "images" / "val"
    train_labels = config.OUTPUT_DIR / "labels" / "train"
    val_labels = config.OUTPUT_DIR / "labels" / "val"
    
    for d in [train_images, val_images, train_labels, val_labels]:
        d.mkdir(parents=True, exist_ok=True)
    
    # Load annotations
    print(f"\nLoading annotations from: {config.SOURCE_ANNOTATIONS}")
    with open(config.SOURCE_ANNOTATIONS) as f:
        data = json.load(f)
    
    images = data['images']
    print(f"Found {len(images)} images")
    
    # Shuffle and split
    random.seed(config.SEED)
    random.shuffle(images)
    
    split_idx = int(len(images) * config.TRAIN_RATIO)
    train_data = images[:split_idx]
    val_data = images[split_idx:]
    
    print(f"Train: {len(train_data)}, Val: {len(val_data)}")
    
    # Process train
    print("\nProcessing training data...")
    for img_data in tqdm(train_data, desc="Train"):
        process_image(img_data, train_images, train_labels)
    
    # Process val
    print("\nProcessing validation data...")
    for img_data in tqdm(val_data, desc="Val"):
        process_image(img_data, val_images, val_labels)
    
    # Create YAML config
    yaml_path = config.OUTPUT_DIR / "tree_canopy.yaml"
    yaml_content = f"""# Tree Canopy Detection Dataset
# Auto-generated by convert_to_yolo.py

path: {config.OUTPUT_DIR.absolute()}
train: images/train
val: images/val

names:
  0: individual_tree
  1: group_of_trees

# Dataset info
nc: 2  # number of classes
"""
    
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    
    print(f"\n{'='*60}")
    print("CONVERSION COMPLETE!")
    print(f"{'='*60}")
    print(f"Output: {config.OUTPUT_DIR}")
    print(f"Train images: {len(list(train_images.glob('*')))}")
    print(f"Val images: {len(list(val_images.glob('*')))}")
    print(f"YAML config: {yaml_path}")
    print(f"{'='*60}")


def process_image(img_data, images_dir, labels_dir):
    """Process a single image and its annotations."""
    filename = img_data['file_name']
    src_path = config.SOURCE_IMAGES / filename
    
    if not src_path.exists():
        return
    
    # Copy image (convert to jpg for YOLO)
    dst_name = filename.replace('.tif', '.jpg').replace('.tiff', '.jpg')
    dst_path = images_dir / dst_name
    
    # YOLO works better with jpg, but for tif we'll just copy
    # Actually, ultralytics supports tif, so let's keep it
    dst_name = filename
    dst_path = images_dir / dst_name
    shutil.copy(src_path, dst_path)
    
    # Get dimensions
    img_width = img_data.get('width', 1024)
    img_height = img_data.get('height', 1024)
    
    # Create label file
    label_name = dst_name.replace('.tif', '.txt').replace('.tiff', '.txt')
    label_path = labels_dir / label_name
    
    lines = []
    for ann in img_data.get('annotations', []):
        class_name = ann.get('class', 'individual_tree')
        class_id = config.CLASS_MAP.get(class_name, 0)
        
        polygon = ann.get('segmentation', [])
        if len(polygon) < 6:  # Need at least 3 points
            continue
        
        # Convert to normalized coords
        normalized = convert_polygon_to_yolo(polygon, img_width, img_height)
        
        # Format: class_id x1 y1 x2 y2 ...
        coords_str = ' '.join([f"{c:.6f}" for c in normalized])
        lines.append(f"{class_id} {coords_str}")
    
    with open(label_path, 'w') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    convert_annotations()
